getyoti/yoti-ruby-sdk

lib/yoti/configuration.rb, lib/yoti/request.rb, spec/yoti/configuration_spec.rb
Added sdk_identifier to list of accessible instance vars & added new tests
=> [SDK-118]:  Added sdk_identifier to list of accessible instance vars

CHANGELOG.md, CONTRIBUTING.md, README.md, Rakefile, examples/rails/app/controllers/yoti_controller.rb, examples/rails/app/views/yoti/profile.html.erb, examples/sinatra/app.rb, examples/sinatra/views/profile.erb, lib/yoti/activity_details.rb, lib/yoti/protobuf/v1/protobuf.rb, lib/yoti/version.rb, spec/yoti/client_spec.rb, spec/yoti/protobuf/protobuf_spec.rb
Removed PNG/JPEG switch cases from protobuf
Added and removed the relevant tests
=> [SDK-136] Added Base64 selfie helper method

CHANGELOG.md, README.md, lib/yoti/activity_details.rb, lib/yoti/version.rb, spec/yoti/activity_details_spec.rb
Pretty basic, I didn't add a test because I don't have a protobuf response with the age attribute mocked.
=> [SDK-285]: Add age_verified helper

README.md, examples/rails/app/controllers/yoti_controller.rb, examples/sinatra/app.rb
Tested profile page for both examples on Windows with bash
=> SDK-209: Update `token` to be referred to as `one time use token`

lib/yoti/protobuf/main.rb, spec/yoti/protobuf/protobuf_spec.rb
=> SDK-871: Handle INT values

lib/yoti/protobuf/main.rb, spec/yoti/activity_details_spec.rb, spec/yoti/protobuf/protobuf_spec.rb
- Allows empty string attributes
- Excludes empty non-string values
=> SDK-861: Allow empty string attributes

spec/yoti/activity_details_spec.rb
- Added test coverage for _Remember Me ID_ not being present
- Added test coverage for _Parent Remember Me ID_ not being present
=> SDK-815: Add test coverage for Remember Me ID not being present

examples/aml_check/app.rb
=> SDK-917: Correct zip code

lib/yoti/http/signed_request.rb, spec/yoti/http/signed_request_spec.rb
- `X-Yoti-SDK-Version` request header with value `Ruby-x.x.x`
=> SDK-671: Add version request header

lib/yoti/data_type/anchor.rb, lib/yoti/data_type/profile.rb, lib/yoti/util/anchor_processor.rb
- Attribute and anchor documentation
=> SDK-996: Update attribute and anchor documentation

lib/yoti/configuration.rb, spec/yoti/configuration_spec.rb
- Allowing full API endpoint configuration to be set
=> SDK-1015: Allow full API endpoint to be set

lib/yoti/activity_details.rb
=> SDK-1016: Update timestamp documentation

README.md
- Documented structured postal address in README
=> SDK-939: Document structured postal address

README.md
=> SDK-1052: Add anchors getter to README

examples/rails/app/controllers/yoti_controller.rb, examples/rails/app/views/yoti/index.html.erb, examples/sinatra/app.rb, examples/sinatra/views/index.erb
> Following #54 
- `clientSdkId` to example button config
=> SDK-1041: Modal QR

README.md
- Developer docs URLs to https://developers.yoti.com
=> SDK-1087: Update developer docs URL in README

README.md
=> SDK-478: Fix readme instructions for Rails to have the correct port

examples/rails/app/views/yoti/profile.html.erb, examples/sinatra/views/profile.erb, lib/yoti.rb, lib/yoti/activity_details.rb, lib/yoti/data_type/age_verification.rb, lib/yoti/data_type/attribute.rb, lib/yoti/data_type/base_profile.rb, lib/yoti/data_type/profile.rb, lib/yoti/util/age_processor.rb, spec/yoti/data_type/age_verification_spec.rb, spec/yoti/data_type/profile_spec.rb
- `Yoti::AgeVerification`
- `Yoti::Profile`
- `#age_verifications`
- `#find_age_over_verification(age)`
- `#find_age_under_verification(age)`
- `Yoti::ActivityDetails#age_verified`
- `Yoti::AgeProcessor`
=> SDK-579: Age Verifications

lib/yoti/sandbox/sandbox.rb, spec/yoti/sandbox/sandbox_spec.rb
- Logging sandbox info message
=> SDK-1268: Log sandbox info message

Gemfile, examples/rails/app/controllers/yoti_controller.rb, examples/rails/app/views/yoti/dynamic_share.html.erb, examples/rails/config/routes.rb, examples/sinatra/app.rb, examples/sinatra/views/dynamic_share.erb, lib/yoti.rb, lib/yoti/dynamic_share_service/dynamic_scenario.rb, lib/yoti/dynamic_share_service/extension/extension.rb, lib/yoti/dynamic_share_service/extension/location_constraint_extension.rb, lib/yoti/dynamic_share_service/extension/transactional_flow_extension.rb, lib/yoti/dynamic_share_service/policy/dynamic_policy.rb, lib/yoti/dynamic_share_service/policy/wanted_attribute.rb, lib/yoti/dynamic_share_service/share_url.rb, spec/sample-data/responses/share_url.json, spec/yoti/dynamic_share_service/dynamic_scenario_spec.rb, spec/yoti/dynamic_share_service/extension/extension_spec.rb, spec/yoti/dynamic_share_service/extension/location_constraint_extension_spec.rb, spec/yoti/dynamic_share_service/extension/transactional_flow_extension_spec.rb, spec/yoti/dynamic_share_service/policy/dynamic_policy_spec.rb, spec/yoti/dynamic_share_service/policy/wanted_attribute_spec.rb, spec/yoti/dynamic_share_service/share_url_spec.rb
* Add DynamicSharingService module to wrap dynamic scenario features
* Add DynamicScenario, DynamicPolicy, WantedAttribute objects
* Add create_share_url to create a dynamic share from a DynamicScenario.
* Add /dynamic-share endpoint to example projects.
=> SDK-726: dynamic scenarios

yoti.gemspec
Change dependency in accordance with gem's recommendation.
=> SDK-1108: Update dependency on google-protobuf

lib/yoti/protobuf/main.rb, spec/yoti/dynamic_share_service/extension/thirdparty_attribute_extension_spec.rb, spec/yoti/protobuf/protobuf_spec.rb, spec/yoti/share/extra_data_spec.rb
* Add unit test for to_json method of ThirdPartyAttributeDefinition.
=> SDK-1384: Add testing for ThirdPartyAttributeDefinition

lib/yoti/activity_details.rb, lib/yoti/dynamic_share_service/extension/thirdparty_attribute_extension.rb, lib/yoti/protobuf/main.rb, lib/yoti/share/attribute_issuance_details.rb, lib/yoti/version.rb, sonar-project.properties, spec/yoti/activity_details_spec.rb, spec/yoti/dynamic_share_service/extension/thirdparty_attribute_extension_spec.rb, spec/yoti/protobuf/protobuf_spec.rb, spec/yoti/share/attribute_issuance_details_spec.rb, spec/yoti/share/extra_data_spec.rb
* JSON payload for thirdparty extension to match api specification
=> Release 1.6.1

.travis.yml, README.md, Rakefile, sonar-project.properties, yoti.gemspec
- Added SonarCloud to Travis
- Added SonarCloud badges to README
- Removed Coveralls
=> SDK-1393: Setup SonarCloud

examples/rails/app/controllers/yoti_controller.rb, examples/rails/app/views/yoti/profile.html.erb, examples/sinatra/app.rb, examples/sinatra/views/profile.erb
- Remove deprecated code from examples
=> SDK-1331: Remove deprecated code from examples

examples/rails/Gemfile
=> SDK-1398: Update demo dependencies

sonar-project.properties
- Excluded files from coverage report
=> SDK-1393: Sonar Coverage Exclusions

lib/yoti/dynamic_share_service/policy/dynamic_policy.rb, spec/yoti/dynamic_share_service/policy/dynamic_policy_spec.rb
- Add dynamic scenario support for document images
- Add dynamic scenario source constraint support for document details
=> SDK-1616: Dynamic Scenario Document Images

examples/doc_scan/app/views/yoti/index.html.erb
- Updated Doc Scan demo iframe to allow full screen
=> SDK-1683: Update Doc Scan demo iframe

.pre-commit-config.yaml, yoti.gemspec
=> SDK-1141: Add pre-commit config

lib/yoti/doc_scan/session/create/requested_document_authenticity_check.rb, lib/yoti/doc_scan/session/create/requested_face_match_check.rb, spec/yoti/doc_scan/session/create/requested_document_authenticity_check_spec.rb
- Manual check config to authenticity checks
=> SDK-1735: Add manual check config to authenticity checks

examples/doc_scan/app/views/yoti/success.html.erb, lib/yoti/doc_scan/session/create/session_specification.rb, lib/yoti/doc_scan/session/retrieve/get_session_result.rb, spec/yoti/doc_scan/session/create/session_specification_spec.rb, spec/yoti/doc_scan/session/retrieve/get_session_result_spec.rb
- Support for blocking and retrieving biometric consent
=> SDK-1742: Biometric Consent

examples/doc_scan/app/controllers/yoti_controller.rb, examples/doc_scan/app/views/yoti/success.html.erb
- ID document comparison to demo
=> SDK-1722: ID Document Comparison Demo

lib/yoti/doc_scan/session/retrieve/page_response.rb, spec/yoti/doc_scan/session/retrieve/page_response_spec.rb
- Document page frames support
=> SDK-1770: Support document page frames

examples/doc_scan/app/views/yoti/success.html.erb
- Document page frames are now included in demo
=> SDK-1770: Add document page frames to demo

lib/yoti/activity_details.rb, lib/yoti/data_type/document_details.rb, lib/yoti/ssl.rb, lib/yoti/util/age_processor.rb
- Updated deprecation messages
=> NA: Update deprecation messages

examples/doc_scan/app/controllers/yoti_controller.rb, examples/doc_scan/app/views/yoti/privacy.html.erb, examples/doc_scan/config/routes.rb, lib/yoti/doc_scan/session/create/sdk_config.rb, spec/yoti/doc_scan/session/create/sdk_config_spec.rb
- Support for custom privacy policy URL
=> SDK-1822: Privacy Policy URL
